[build]
  base = "frontend"
  publish = "build"
  command = "yarn install && yarn build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
