name: Build and Upload APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Install Capacitor + Android
        run: |
          cd frontend
          npm install @capacitor/core @capacitor/cli
          npx cap sync android

      - name: Build APK
        run: |
          cd frontend/android
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: quickstash-apk
          path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
